logger:
  level: INFO
  appender:
    name: FILE
    class: FileAppender # | ConsoleAppender
    file: app.log
    # pattern supports the following keys: date, level, pid, logger, fiber, msg
    pattern: "[%{date}] [%{level}] [%{logger}] [%{fiber}] - %{msg}"
    # immediate_flush: true
  # severity:
  #   *: DEBUG
  #   My::Class: INFO
