logger:
  level: INFO
  appender:
    name: FILE
    class: FileAppender # | ConsoleAppender
    file: app.log
    # immediate_flush: true
    # formatter: [%date{ISO8601}] [%level] [%logger] [%thread] [%X{akkaSource}] - %msg%n</pattern>
  # severity:
  #   *: DEBUG
  #   My::Class: INFO
